name: Deploy via SSH (Nginx Nativo)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4



      - name: Testar se o segredo existe
        run: |
          if [ -z "${{ secrets.REMOTE_HOST }}" ]; then
            echo "ERRO: A variável REMOTE_HOST está VAZIA!"
            exit 1
          else
            echo "Sucesso: O segredo foi carregado."
          fi
      - name: Enviar arquivos para o servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "."
          target: "/var/www/leonilso"

      - name: Ajustar permissões finais
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            sudo chown -R leo:www-data /var/www/leonilso
            sudo chmod -R 775 /var/www/leonilso